export { Sound } from './Sound.ts';
export type { SoundOptions } from './Sound.ts';
export { onCaption } from './Captions.ts';
export type { CaptionEvent } from './Captions.ts';
export { Music } from './Music.ts';
export type { MusicOptions } from './Music.ts';
export { createAudio } from './Playable.ts';
export type { Playable } from './Playable.ts';
export { Orchestrator } from './Orchestrator.ts';
export type { OrchestratorState } from './Orchestrator.ts';
export { synthesizeTone, playTone } from './Synth.ts';
export type { Waveform, ToneOptions } from './Synth.ts';
export { parseMidi, scheduleMidi, noteToFrequency, MidiPlayer } from './Midi.ts';
export type { MidiFile, MidiEvent, MidiNoteEvent, MidiTempoEvent, ScheduledNote, MidiPlayerOptions } from './Midi.ts';
