export { StatBlock } from './StatBlock.ts';
export type { Stats, Modifier, ModifierOp, DerivedStat, StatBlockOptions } from './StatBlock.ts';
export { Progression, powerCurve } from './Progression.ts';
export type { GrowthCurve } from './Progression.ts';
export { skillCheck } from './skillCheck.ts';
export { SkillPoints } from './SkillPoints.ts';
export type { SkillPointsOptions } from './SkillPoints.ts';
export { EquipmentSlots } from './Equipment.ts';
export type { EquippableItem, EquipmentOptions, SavedEquipment } from './Equipment.ts';
export { Inventory } from './Inventory.ts';
export type { InventoryItem, InventoryOptions, ItemDefinition, SavedInventory, SavedInventoryItem } from './Inventory.ts';
export { craft } from './craft.ts';
export type { Recipe } from './craft.ts';
export { applyStatusEffect } from './StatusEffect.ts';
export type { EffectClock, StatusEffectOptions, StatusEffectHandle } from './StatusEffect.ts';
export { identify, enchant, damageItem, repairItem } from './ItemState.ts';
export type { AffixUpgradePolicy } from './ItemState.ts';
export { applyItemStatusEffect } from './ItemStatusEffect.ts';
export type { ItemStatusEffectOptions, ItemStatusEffectHandle } from './ItemStatusEffect.ts';
export { Charges } from './Charges.ts';
export type { ChargesOptions } from './Charges.ts';
export { rollLoot } from './Loot.ts';
export type { LootEntry, LootTable } from './Loot.ts';
export { Advancement } from './Advancement.ts';
export type { AdvancementOption, AdvancementTier, AdvancementTierKind, AdvancementTrack } from './Advancement.ts';
export { rollAffix, affixOf, applyAffix, removeAffix, copyAffix, matchesContext } from './Affix.ts';
export type { AffixDef, AffixTable, AffixTrigger, AttackKind, AffixContext } from './Affix.ts';
export { scaledModifiers } from './Scaling.ts';
export type { LevelScale } from './Scaling.ts';
export { assignAppearances, Appearances } from './Appearances.ts';
export type { AppearanceTable } from './Appearances.ts';
export { buy, sell } from './Shop.ts';
export type { Price, ShopOptions } from './Shop.ts';
export { canAfford, spend, refund, convertToCharges } from './Resource.ts';
export type { ResourceCost } from './Resource.ts';
export { Barrier } from './Barrier.ts';
export type { BarrierLayer } from './Barrier.ts';
export { assignTraits } from './Traits.ts';
export type { TraitDef, AssignedTrait } from './Traits.ts';
export { AuraField } from './Aura.ts';
export type { AuraDef, AuraParticipant } from './Aura.ts';
export { SupportLedger } from './Support.ts';
export type { SupportLevel, SupportChange, SupportSave } from './Support.ts';
export { buildEntity, buildEntities } from './EntityTemplate.ts';
export type { EntityTemplateRow, EntityTemplateCatalog, BuiltEntity } from './EntityTemplate.ts';
